// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

// Injectors from wire.go:

func initShopCart() (*ShopCat, error) {
	productList, err := NewProductList()
	if err != nil {
		return nil, err
	}
	shopCat, err := NewShop(productList)
	if err != nil {
		return nil, err
	}
	return shopCat, nil
}
